# Generated by Django 5.0.2 on 2024-03-04 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ec2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec2_id', models.CharField(max_length=255)),
                ('instance_type', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=False)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45)),
                ('ec2_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awsAssetApp.ec2')),
                ('organisation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awsAssetApp.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='ec2',
            name='organisation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awsAssetApp.organisation'),
        ),
    ]
