# Generated by Django 5.0.2 on 2024-03-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsAssetApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elasticip',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
