# Generated by Django 5.0.2 on 2024-03-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awsAssetApp', '0002_elasticip_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elasticip',
            name='isActive',
        ),
    ]
