# Generated by Django 5.0.2 on 2024-03-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsAssetApp', '0003_remove_elasticip_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='elasticip',
            name='current_status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
