# Generated by Django 5.0.2 on 2024-03-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsAssetApp', '0004_elasticip_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2',
            name='instance_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ec2',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ec2',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
