# Generated by Django 5.0.2 on 2024-03-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsAssetApp', '0006_ec2_awsstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2',
            name='awsStatus',
            field=models.CharField(default='Standby', max_length=255),
        ),
    ]
